### ISSUE TITLE
[Question] Value time sleep

### ISSUE THREAD

**Issue by jlstanus** [Sanderi44/Lidar-Lite#4]
Hello,
Thanks for your code.
I have the lidar V1. I tested and it works except +/- 5 cm error but maybe it's my device that took shocks.

I would know how you defined the sleep time. 
Because the v1 has 100Hz sampling vs 500 Hz v2 and V3.
Did you do adaptations with frequency?

Thanks.

**Comment by Sanderi44** [comment]
Hi,

I did not do any testing with the frequency, so feel free to change it
so that it works well. As Patrick brought up in his issue, the readAndWait
function should look like this:

def readAndWait(self, register):
self.bus.write_byte(self.address, register)
res = self.bus.read_byte(self.address)
return res

This is untested, but if it works you may not need a sleep at all.  Please
let me know how it goes.

Thanks,

Sander

**Comment by dacaito** [comment]
Hi!

Thanks for the library, so far it works great for me.

I was curious about the 10ms delays , what was the reasoning behind them?

I've commented them out an on my rpi3 with the Lidar-Lite v3 it's working fine so far. Checked it with an oscilloscope and everything looks OK.
